# Generated by Django 5.2.1 on 2025-06-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Proveedor')),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Food_Filling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Tipo de relleno')),
                ('fk_food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_type.food_type')),
            ],
            options={
                'db_table': 'food_filling',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de relleno disponible')),
                ('fk_food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_type.food_type')),
                ('fk_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_filling.supplier')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
