# Generated by Django 5.2.1 on 2025-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_filling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier',
            field=models.IntegerField(choices=[(1, 'Empresas Polar'), (2, 'Granos Pantera'), (3, 'Alimentos Mary'), (4, 'Hiper Verduras de Aragua C.A'), (5, 'Embutidos Frío Carnes')], null=True, verbose_name='Proveedor'),
        ),
    ]
