# Generated by Django 5.2.1 on 2025-06-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_filling', '0003_food_filling_type_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_filling',
            name='fk_food_type',
        ),
    ]
