# Generated by Django 5.2.1 on 2025-06-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_filling', '0004_remove_food_filling_fk_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_filling',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Cantidad de relleno'),
        ),
    ]
