# Generated by Django 5.2.1 on 2025-06-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_filling', '0005_food_filling_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='fk_food_type',
        ),
        migrations.AddField(
            model_name='stock',
            name='fk_food_filling',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_filling.food_filling'),
            preserve_default=False,
        ),
    ]
