# Generated by Django 5.2.1 on 2025-06-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_filling', '0006_remove_stock_fk_food_type_stock_fk_food_filling'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_filling_type_details',
            name='needed_quantity',
            field=models.IntegerField(default='100', verbose_name='Cantidad requerida de relleno'),
        ),
        migrations.AlterField(
            model_name='food_filling',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Cantidad de relleno por unidad'),
        ),
    ]
