# Generated by Django 5.2.1 on 2025-06-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_filling', '0007_food_filling_type_details_needed_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_filling',
            name='quantity',
            field=models.IntegerField(default='100', null=True, verbose_name='Cantidad de relleno por unidad'),
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(verbose_name='Cantidad solicitada')),
                ('status', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobado'), (3, 'Rechazado')], default='1', verbose_name='Estado de la solicitud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fk_food_filling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_filling.food_filling', verbose_name='Relleno solicitado')),
                ('fk_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_filling.supplier', verbose_name='Proveedor')),
            ],
            options={
                'db_table': 'stock_request',
            },
        ),
    ]
