# Generated by Django 5.2.1 on 2025-06-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_filling', '0008_alter_food_filling_quantity_stockrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_filling',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockrequest',
            name='status',
        ),
    ]
