# Generated by Django 5.2.1 on 2025-06-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_filling', '0009_remove_food_filling_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockRequest',
        ),
    ]
