# Generated by Django 5.2.1 on 2025-06-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_filling', '0010_delete_stockrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(default=1, max_length=45, verbose_name='Dirección de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default=1, max_length=45, verbose_name='Nombre de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.IntegerField(default=1, verbose_name='Numero telefónico de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='rif',
            field=models.CharField(default=1, max_length=45, verbose_name='RIF de la empresa'),
            preserve_default=False,
        ),
    ]
