# Generated by Django 5.2.1 on 2025-06-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_filling', '0011_remove_supplier_supplier_supplier_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Número telefónico de la empresa'),
        ),
    ]
