# Generated by Django 5.2.1 on 2025-06-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Tipo de arepa')),
                ('price', models.IntegerField(verbose_name='Precio de la arepa')),
            ],
            options={
                'db_table': 'food_type',
            },
        ),
    ]
