# Generated by Django 5.2.1 on 2025-06-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_type',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio de la arepa'),
        ),
    ]
