# Generated by Django 5.2.1 on 2025-06-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0002_alter_food_type_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_type',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Visible?'),
        ),
    ]
