# Generated by Django 5.2.1 on 2025-06-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre del cliente')),
                ('lastname', models.CharField(max_length=45, verbose_name='Apellido del cliente')),
                ('address', models.CharField(max_length=45, verbose_name='Dirección del cliente')),
                ('phone_number', models.IntegerField(verbose_name='Numero telefónico del cliente')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Modo de pago')),
            ],
            options={
                'db_table': 'payment_type',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='Precio total')),
                ('fk_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.client')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de arepas pedidas')),
                ('fk_food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_type.food_type')),
                ('fk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('fk_payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.payment_type')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
