# Generated by Django 5.2.1 on 2025-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_type',
            name='name',
        ),
        migrations.AddField(
            model_name='payment_type',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Pago Móvil'), (3, 'Tarjeta')], null=True, verbose_name='Modo de pago'),
        ),
    ]
