# Generated by Django 5.2.1 on 2025-06-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_payment_type_name_payment_type_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identity_number',
            field=models.IntegerField(default=1, verbose_name='Cédula del cliente'),
            preserve_default=False,
        ),
    ]
