# Generated by Django 5.2.1 on 2025-06-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_client_identity_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_type',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='payment_type',
            name='name',
            field=models.CharField(default=1, max_length=45, verbose_name='Modo de pago'),
            preserve_default=False,
        ),
    ]
