# Generated by Django 5.2.1 on 2025-10-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_payment_type_payment_type_payment_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Número telefónico del cliente'),
        ),
    ]
